### ISSUE TITLE
Incorrect deployment exception returned when several apps with the same name are deployed over the lifetime of a server

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/liberty-arquillian#15]
##### Issue Overview

When an application fails to deploy, the container scans the log file to work out why it failed. It scans from the start of the log file, looking for lines which either say "myApp started" or "myApp failed to start".

If two apps with the same name are deployed over the course of a test run and the second one fails to deploy, this code will find the log entry for when the first app either deployed successfully or failed to deploy.

##### Expected Behaviour

When the second app fails to start, the container should identify the correct log line.

##### Current Behaviour

The container reports the states from the first app.

In my case, an app with the same name had previously deployed successfully. The resulting error was:
```
org.jboss.arquillian.container.spi.client.container.DeploymentException: Application ftCircuitBreaker started unexpectedly even though it never reached the STARTED state. This should never happen.
	at io.openliberty.arquillian.managed.WLPManagedContainer.throwDeploymentException(WLPManagedContainer.java:1191)
	at io.openliberty.arquillian.managed.WLPManagedContainer.checkApplicationStatus(WLPManagedContainer.java:964)
	at io.openliberty.arquillian.managed.WLPManagedContainer.waitForApplicationTargetState(WLPManagedContainer.java:925)
	at io.openliberty.arquillian.managed.WLPManagedContainer.deploy(WLPManagedContainer.java:420)
	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:151)
```

**Comment by hutchig** [comment]
ref: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=255624
